---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - recipe[apt]
    - recipe[et_worker]
    - recipe[et_worker::zonemanager]
    attributes:
      route53:
        aws_user: Route53_test
        zones:
        - evertruetest.com
