---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  iam_profile_name: test-et_worker-zonemanager
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      tags:
        Name: et_worker-default-ubuntu-1404
    run_list:
      - recipe[apt]
      - recipe[et_worker]
      - recipe[et_worker::zonemanager]
    attributes:
      route53:
        aws_user: Route53_test
        zones:
          - evertruetest.com
