---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  environments_path: <%= ENV['CHEF_REPO'] %>/environments
  data_bags_path: <%= ENV['CHEF_REPO'] %>/data_bags
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - recipe[et_worker]
